# C++ compiler
CC = g++

# Compiler flags
CFLAGS = -Wall -std=c++11

# External libraries to include
LIBRARIES = -lsfml-graphics -lsfml-window -lsfml-system

# Build all targets
all:

Mode7Demo:
	$(CC) $(CFLAGS) ./src/Mode7Demo.cpp -o Mode7Demo $(LIBRARIES)

clean:
	rm CascadingBackground
