# C++ compiler
CC = g++

# Compiler flags
CFLAGS = -Wall -std=c++11

# External libraries to include
LIBRARIES = -lsfml-graphics -lsfml-window -lsfml-system

# Build all targets
all: OverworldDemo

OverworldDemo:
	$(CC) $(CFLAGS) ./src/OverworldDemo.cpp -o OverworldDemo $(LIBRARIES)

clean:
	rm CascadingBackground
